-- Phase 1: Database Foundation — applied via prisma db push 2026-05-10
-- All changes additive, zero breaking changes

CREATE TYPE "SprintStatus" AS ENUM ('PLANNING', 'ACTIVE', 'COMPLETED');
CREATE TYPE "IssueLinkType" AS ENUM ('BLOCKS', 'RELATES_TO', 'DUPLICATES', 'CLONES', 'SPLIT_FROM');
CREATE TYPE "ActivityAction" AS ENUM ('CREATED','UPDATED','DELETED','RESTORED','COMMENTED','MOVED','ASSIGNED','UNASSIGNED','LABELED','UNLABELED','LINKED','UNLINKED','STATUS_CHANGED','PRIORITY_CHANGED','POINTS_CHANGED','DUE_DATE_CHANGED','SPRINT_ADDED','SPRINT_REMOVED','CHECKLIST_ADDED','CHECKLIST_COMPLETED','ATTACHMENT_ADDED','ATTACHMENT_REMOVED','WATCHER_ADDED','WATCHER_REMOVED');
CREATE TYPE "NotificationType" AS ENUM ('ISSUE_ASSIGNED','ISSUE_UNASSIGNED','ISSUE_MENTIONED','ISSUE_COMMENTED','ISSUE_STATUS_CHANGED','ISSUE_RESOLVED','SPRINT_STARTED','SPRINT_COMPLETED','PROJECT_MEMBER_ADDED','PROJECT_MEMBER_REMOVED');
ALTER TABLE "Issue" ADD COLUMN "storyPoints" INTEGER, ADD COLUMN "completedAt" TIMESTAMP(3), ADD COLUMN "deletedAt" TIMESTAMP(3), ADD COLUMN "parentId" TEXT, ADD COLUMN "sprintId" TEXT;
ALTER TABLE "Project" ADD COLUMN "key" TEXT;

